language: node_js

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node-modules

install: yarn --frozen-lockfile --ignore-scripts

script:
  # Force eslint to exit 0 even if errors occur until we land our first package.
  - yarn lint; exit 0
  - yarn format

after_success:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: demo
  on:
    branch: master
