language: node_js

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node-modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile --ignore-scripts

script:
  - yarn lint
  - yarn format
  - yarn test:all --coverage --runInBand

after_success:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: demo
  on:
    branch: master
